AllCops:
  NewCops: enable

# Those metrics are way too arbitrary.
Metrics/AbcSize:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false

# My preferred style
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/IfUnlessModifier:
  Enabled: false
Style/MethodCallWithoutArgsParentheses:
  Enabled: false
Style/DefWithParentheses:
  Enabled: false
Style/StringLiteralsInInterpolation:
  Enabled: false
Style/StderrPuts:
  Enabled: false
Style/ModuleFunction:
  Enabled: false
